language: generic
branches:
  only:
    - gh-pages
deploy:
  provider: s3
  region: us-west-2
  access_key_id:
    secure: fTsWVidMnfnn03jB/0ntR1exFGIFJ47YTwQPG8AHIkVVMPpGxmI6ikChVBFh+5ECYJjpGfw2No1ardfTi3GNaXVCP44r0FOZ+uxjL4dR6x0oFP5zF74pdNjqNA3tNCRMurYn3mdRH3OFEgvVakNJmXnoyQnLJVTbc04DIhzrXPrcnBr9hC7Zg5VfQmqxHaKlPLsViv2Qn5w4h8h/+/d9g+d0ntVVot9FLtuJsN2H6SfeHaoZFLCF3rPJOI6HjM0FhtuQ98UXXC8G/5KOsEgFMdJdM2+KrB9cqcp/t6yeb7hBjCb8+D7O4oxE7O5yl2jWnTijQ98bSJaMoyuFE7Y3YfO98fl17KEaMHlil9YZTx0TLwru8pF2djXCaU9i0d6GzLxFiQ2Fomt8qHBvMSYtbP3i3MFAyYs7+tnHbjfP0lEm0T6nLgMTAV7aZ9uAxsP9MFfiFMTe9sVUhjJVxLYLfKdAtpPv5M6trOMc32f4gZVJ7xeEXc5WVDvFvwGEfZ5sBMy2dQX3lp3BDH7oIDHugVDcT+N5JGVYSOSc5ALW+toRtMPEAyncJZZbY9BgJizE+rrvKQnwjRwOfYiYDpxtQFn0EwgodXJ+Gk16dDvRXdELa7vLPZ2YoIYeQ22khgDP6bL6zUw2qRl3TBoG98qRLircVJzMRarCvzNCRWErfYI=
  secret_access_key:
    secure: ib5n5P5MLlw3UaE1kOFZ10dkfFRaRI7fsl1M8ziH+/EAnTG8gGp0g63Gd7rfg/kl2yIROmCEeH1Fb+zCkPoCXPuz4TbtwXhIJ1DS9pP53+7+Rhh5z6vGdPfLW1XtnoUZ9MMrXjwG7sJF84cUe/aslDD7WPBZgvrXbZj0N1/TCabiin/pN++9cwMNr0L9lXJW8JCwW0G5En7BRleckVYWPSFZPgAyi21PJxzk6/fQucITdoUYMHcJAVSZbdl6+2b/z9voCfvIJha643UxvM34Y20+7UiJqBX54dPrnPuaBC1ZDPvEZeRAhxmJvUVIzZgGsBa/2dWeRRWpIQ7DsAZszzXhPNxE7/LooV2+qHFislR/eKQCI3YoBwsOVcKlFvBevFeoUtEI2vIUQzJV/DjDzLaNY/AZIHNkkqVHcdETN0fqcvQpgRYeoYKRCbCjc7iIjMuL9AsETSdpxOuVuPwHw40Ui7YJEleVROJyQ23Zz3gIgi4CE4LG7BeWTHSQyUnIGAechtfcg3smYwgitrNFtOlw65inGt8PF9E0WEIoNrINgV/loqwmueeJOBhV2qS9xpwpHhB7klZkeTJTzRMzdX7GNiJxVmcVgU/h7o7tK0S+PgXqMjRSdwSFcAm9m4iqCb27gVQSp9bFWvKeZPi9VhWf4Cn3G+TnL5cWNrE74zc=
  bucket: mixed-content-tests-mozilla.org
  acl: public_read
  on:
    repo: mozilla/mixed-content-tests
    branch: gh-pages
